# See: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci

language: node_js
dist: trusty
node_js:
  - 10
addons:
  apt:
    packages:
      - libnss3
script:
  - yarn test
  - yarn prettier --list-different
  - yarn eslint
  - yarn tsc
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
